[package]
name = "zerda"
version = "0.1.0"
authors = ["FoxBoxPDX <foxboxpdx@gmail.com>"]

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.3"
regex = "0.2"
lazy_static = "0.2"
base64 = "0.5"
time = "0.1"
openssl = "0.9"
